---
production: &default
  serverPort: 3000
  baseUrl: http://www.intranet.com
  baseApi: /api/
  views:
    engine: .hbs
    extension: .hbs
    layout: main
  html:
    minify: true
    css:
      compress: true
      stylusPrecompile: true
  controllers:
    default: home
  languages:
    default: en
    list: [en, es]
  security:
    secret: stud10v1ct0ry.com
  session:
    cookieDomain: .intranet.com
    maxAge: 86400
    cookiePrefix: 'svSession_'
    path: '/'
    httpOnly: true

stage: &stage
  <<: *default
  baseUrl: http://stage.intranet.com

latest: &latest
  <<: *stage
  baseUrl: http://latest.intranet.com

development:
  <<: *latest
  baseUrl: http://local.intranet.com
  html:
    minify: false
    css:
      compress: false
      stylusPrecompile: false
